In [ ]:
import pandas as pd
import re

col = {'M': 'masters', 'D': 'derivatives'}
df1 = pd.read_csv('../ofm-arche/handles.csv')
df = pd.read_csv('OFM_Graz_Digitalisate_2024-10-11-1.csv')
df3 = pd.read_csv('output.csv')
df4 = pd.read_csv('handles_copy.csv')

In [36]:
import time

In [4]:
import pandas as pd
df = pd.read_csv('OFM_Graz_Digitalisate_2024-10-11-1.csv')
df

,Fördernehmer_in,eindeutige Nummer des Digitalisats,Analogfilm,3D,Sonstige,handle_id,Titel des Digitalisats,arche_id,Kommentar (optional)
0,Franziskanerkloster Graz,A-Gf_A63_51-000v_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9112-2,A-Gf_A63_51-000v (derivative),https://hdl.handle.net/21.11115/0000-0013-9111-3,NaN
1,Franziskanerkloster Graz,A-Gf_A63_51-001r_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9114-0,A-Gf_A63_51-001r (derivative),https://hdl.handle.net/21.11115/0000-0013-9113-1,NaN
2,Franziskanerkloster Graz,A-Gf_A63_51-001v_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9116-E,A-Gf_A63_51-001v (derivative),https://hdl.handle.net/21.11115/0000-0013-9115-F,NaN
3,Franziskanerkloster Graz,A-Gf_A63_51-002r_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9118-C,A-Gf_A63_51-002r (derivative),https://hdl.handle.net/21.11115/0000-0013-9117-D,NaN
4,Franziskanerkloster Graz,A-Gf_A63_51-002v_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-911A-A,A-Gf_A63_51-002v (derivative),https://hdl.handle.net/21.11115/0000-0013-9119-B,NaN
...,...,...,...,...,...,...,...,...,...
35421,Franziskanerkloster Graz,A-Gf_S1_76-027v_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-89D5-0,A-Gf_S1_76-027v (master),https://hdl.handle.net/21.11115/0000-0012-6B55-5,NaN
35422,Franziskanerkloster Graz,A-Gf_S1_76-028v_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-89D7-E,A-Gf_S1_76-028v (master),https://hdl.handle.net/21.11115/0000-0012-6B57-3,NaN
35423,Franziskanerkloster Graz,A-Gf_S1_76-VDS_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-89DB-A,A-Gf_S1_76-VDS (master),https://hdl.handle.net/21.11115/0000-0012-6B5C-E,NaN
35424,Franziskanerkloster Graz,A-Gf_S1_76-FKv_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-8CF8-6,A-Gf_S1_76-FKv (master),https://hdl.handle.net/21.11115/0000-0012-6B5A-0,NaN
35425,Franziskanerkloster Graz,A-Gf_S1_76-FKr_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-8CF7-7,A-Gf_S1_76-FKr (master),https://hdl.handle.net/21.11115/0000-0012-6B59-1,NaN

In [ ]:
import pandas as pd
import re
used = []
df = pd.read_csv('OFM_Graz_Digitalisate_2024-10-11-1.csv')
ref = df3 = pd.read_csv('OFM_Graz.csv')
col = {'M': 'masters', 'D': 'derivatives'}
#handle_ids = df['Ressourcenadresse'].dropna().tolist()
for index, row in df.iterrows():
    handle_id = row['Ressourcenadresse']
    arche_id = row["Kontextadresse"]
    img_name = row['eindeutige Nummer des Digitalisats'].replace("Gu", "Gf")
    collection = img_name[-1]
    img_name = img_name.replace("Gu", "Gf").split(".jpg")[0]
    img_name = re.sub(r"^.*A-Gf_", "A-Gf_", img_name)[:-2]
    img_name = re.sub(r"^[\d_]*", "", img_name)
    img_name = re.sub(r"A-Gf_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = re.sub(r"A-Gf_A_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = img_name.replace("view_IMG_0134", "A-Gf_S1_61-VDS").replace('A-Gf_64', 'A-Gf_A64').replace(' ', '').replace('%2B', '_')
    img_name = img_name.replace("67-43", "67_43").replace('.TIF', '').replace('S1_67_', "S1_67-")
    img_name = re.sub(r"(S1_22/A-Gf_S1_2)3", r"\g<1>2", img_name)
    img_name = re.sub(r"(A64_41.*\d)vv", r"\g<1>v", img_name)
    row['eindeutige Nummer des Digitalisats'] = img_name
    elements = ref.loc[ref["eindeutige Nummer des Digitalisats"].str.endswith(f'{img_name}_{collection}')]
    if len(elements) > 0:
        refrow = elements.iloc[0]
        if not ref['Ressourcenadresse'].str.contains(handle_id, case=False, na=False).any():
            if handle_id not in used:
                cl.update_handle(handle_id, refrow["Ressourcenadresse"])
                used.append(handle_id)
            else:
                row['Ressourcenadresse'] = refrow['Ressourcenadresse']    
                used.append(ref['Ressourcenadresse'].replace('@format=tif', ''))
        else:
            row['Ressourcenadresse'] = refrow['Ressourcenadresse']
            used.append(ref['Ressourcenadresse'].replace('@format=tif', ''))
        if not ref['Ressourcenadresse'].str.contains(arche_id, case=False, na=False).any():
            if arche_id not in used:
                used.append(arche_id)
                cl.update_handle(arche_id, refrow["Kontextadresse"]')
            else:
                row["Kontextadresse"]  = refrow["Kontextadresse"]

A-Gf_A67_43-HDS_D
A-Gf_A67_43-HDS_D

In [ ]:
+ A-Gf_S1_72-509_D
- A-Gf_A67_43-HDS_D
- A-Gf_A67_43-HDS_D

In [ ]:

handle_ids = 

handles = list(dict.fromkeys([h.replace('@format=metadata', '')  for h in df2['Kontextadresse'].tolist() + df2['Ressourcenadresse'].tolist() + df3['Ressourcenadresse'].tolist() if h.replace('@format=metadata', '') not in df1['handle_id'].unique()]))

In [15]:
username = "user21.11115-01"  # Replace with your username for basic authentication
password = "X91yuVlwi4"  # Replace with your password for basic authentication

In [17]:
from acdh_handle_pyutils.client import HandleClient

cl = HandleClient(username, password)

In [44]:
# Franziskanerkloster Graz,A-Gf_A63_51-000v_D,,,X,https://hdl.handle.net/21.11115/0000-0013-9112-2,A-Gf_A63_51-000v (derivative),https://hdl.handle.net/21.11115/0000-0013-9111-3,https://hdl.handle.net/21.11115/0000-0013-9111-3@format=metadata
df4 = pd.read_csv('handles_copy.csv')

In [ ]:
used  = []
for index, row in df2.iterrows():
    img_name = row['eindeutige Nummer des Digitalisats'].replace("Gu", "Gf")
    collection = col[img_name[-1]]
    img_name = img_name.replace("Gu", "Gf").split(".jpg")[0]
    img_name = re.sub(r"^.*A-Gf_", "A-Gf_", img_name)[:-2]
    img_name = re.sub(r"^[\d_]*", "", img_name)
    img_name = re.sub(r"A-Gf_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = re.sub(r"A-Gf_A_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = img_name.replace("view_IMG_0134", "A-Gf_S1_61-VDS").replace('A-Gf_64', 'A-Gf_A64').replace(' ', '').replace('%2B', '_')
    img_name = img_name.replace("67-43", "67_43").replace('.TIF', '').replace('S1_67_', "S1_67-")
    img_name = re.sub(r"(S1_22/A-Gf_S1_2)3", r"\g<1>2", img_name)
    img_name = re.sub(r"(A64_41.*\d)vv", r"\g<1>v", img_name)
    subcol = df4.loc[df4["arche_id"].str.contains(collection)] 
    #subcol = df1[df1.loc['arche_id'].astype(str).str.contains(collection)]
    elements = subcol.loc[subcol["arche_id"].str.endswith(f'{img_name}.tif')] 
    # subcol[subcol['arche_id', 'handle_id'].astype(str).str.contains(img_name)]
    flag = False
    if elements.size > 0:
        element_a = elements['arche_id'].iloc[0].strip()
        element_h = elements['handle_id'].iloc[0].strip()
        if len(handles) > 0:
            handle = handles[-1].strip()
            t = 0
            while flag == False:
                t += 1
                try: 
                    cl.update_handle(handle, f'{element_h}@format=tif')
                    flag = True
                except Exception:
                    if t < 10:
                        time.sleep(t)
                    else:
                        with open('notfound', 'a') as f:
                        df4["eindeutige Nummer des Digitalisats"], df4["Titel des Digitalisats"] = zip(
    *df4["Ressourcenadresse"].apply(lambda x: extract_info(x) if isinstance(x, str) else (None, None))
)

# Display the updated DataFrame
            flag = False
            t = 0
            while flag == False:
                try:
                    t += 1
                    handle = cl.register_handle(f'{element_h}@format=tif', full_url=True)
                    flag = True
                except Exception:
                    if t < 20:
                        time.sleep(t)
                    else:
                        with open('notfound', 'a') as f:
                            f.write(f'TIME: {subcol}/{img_name}')
                        continue
    else:
        print(f'NOT FOUND: {subcol}/{img_name}')
        with open('notfound', 'a') as f:
            f.write(f'NOT FOUND: {subcol}/{img_name}')
    if element_h not in used:
        if handle not in used:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},{handle},{row["Titel des Digitalisats"]},,{element_h}\n'
            used.append(handle)
        else:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},X,{row["Titel des Digitalisats"]},,{element_h}\n'
        used.append(element_h)
        with open('output.csv', "a") as f:
            f.write(line)
    else:
        if handle not in used:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},{handle},{row["Titel des Digitalisats"]},,X\n'
            used.append(handle)
        else:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},X,{row["Titel des Digitalisats"]},,X\n'
        with open('failed.csv', "a") as f:
            f.write(line)

KeyboardInterrupt:

In [ ]:
ready = pd.read_csv('ready.csv')
fail = pd.read_csv('fail_torevise.csv')
used  = []
for index, row in df2.iterrows():
    img_name = row['eindeutige Nummer des Digitalisats'].replace("Gu", "Gf")
    collection = col[img_name[-1]]
    img_name = img_name.replace("Gu", "Gf").split(".jpg")[0]
    img_name = re.sub(r"^.*A-Gf_", "A-Gf_", img_name)[:-2]
    img_name = re.sub(r"^[\d_]*", "", img_name)
    img_name = re.sub(r"A-Gf_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = re.sub(r"A-Gf_A_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = img_name.replace("view_IMG_0134", "A-Gf_S1_61-VDS").replace('A-Gf_64', 'A-Gf_A64').replace(' ', '').replace('%2B', '_')
    img_name = img_name.replace("67-43", "67_43").replace('.TIF', '').replace('S1_67_', "S1_67-")
    img_name = re.sub(r"(S1_22/A-Gf_S1_2)3", r"\g<1>2", img_name)
    img_name = re.sub(r"(A64_41.*\d)vv", r"\g<1>v", img_name)
    subcol = ready.loc[ready["Title"].str.endswith(collection[0].upper())]
    subcol = df1.loc[df1["arche_id"].str.contains(collection)] 
    #subcol = df1[df1.loc['arche_id'].astype(str).str.contains(collection)]
    elements = subcol.loc[subcol["arche_id"].str.contains(img_name)]
    rdf = subcol.loc[subcol["arche_id"].str.contains(img_name)]
    rdf = subcol.loc[subcol["arche_id"].str.contains(img_name)]
    # subcol[subcol['arche_id', 'handle_id'].astype(str).str.contains(img_name)]
    if elements.size > 0:
        element_a = elements['arche_id'].iloc[0].strip()
        element_h = elements['handle_id'].iloc[0].strip()
        if len(handles) > 0:
            handle = handles[-1].strip()
            cl.update_handle(handle, f'{element_h}@format=tif')
            handles.pop(-1)
        else:
            handle = cl.register_handle(f'{element_h}@format=tif', full_url=True)
    else:
        print(f'NOT FOUND: {subcol}/{img_name}')
    if element_h not in used:
        if handle not in used:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},{handle},{row["Titel des Digitalisats"]},,{element_h}\n'
            used.append(handle)
        else:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},X,{row["Titel des Digitalisats"]},,{element_h}\n'
        used.append(element_h)
        with open('output.csv', "a") as f:
            f.write(line)
    else:
        if handle not in used:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},{handle},{row["Titel des Digitalisats"]},,X\n'
            used.append(handle)
        else:
            line = f'Franziskanerkloster Graz,{row["eindeutige Nummer des Digitalisats"]},{row["Analogfilm"]},{row["3D"]},{row["Sonstige"]},X,{row["Titel des Digitalisats"]},,X\n'
        with open('failed.csv', "a") as f:
            f.write(line)

In [23]:
random_list = []
for index, row in df2.iterrows():
    img_name = row['eindeutige Nummer des Digitalisats'].replace("Gu", "Gf")
    if "43-HD" in img_name:
        print('a: ', img_name)
    collection = col[img_name[-1]]
    img_name = img_name.replace("Gu", "Gf").split(".jpg")[0]
    img_name = re.sub(r"^.*A-Gf_", "A-Gf_", img_name)[:-2]
    img_name = re.sub(r"^[\d_]*", "", img_name)
    img_name = re.sub(r"A-Gf_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = re.sub(r"A-Gf_A_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = img_name.replace("view_IMG_0134", "A-Gf_S1_61-VDS").replace('A-Gf_64', 'A-Gf_A64').replace(' ', '').replace('%2B', '_')
    img_name = img_name.replace("67-43", "67_43").replace('.TIF', '').replace('S1_67_', "S1_67-")
    img_name = re.sub(r"(S1_22/A-Gf_S1_2)3", r"\g<1>2", img_name)
    img_name = re.sub(r"(A64_41.*\d)vv", r"\g<1>v", img_name)
    if "A67_43-HD" in img_name:
        print(f'B: {collection}/{img_name}')
    random_list.append(f'{collection}/{img_name}')

a:  A-Gf_A64_43-HDS_D
a:  A-Gf_A64_43-HD_D
a:  A-Gf_A67-43-HDS_D
B: derivatives/A-Gf_A67_43-HDS
a:  A-Gf_A67_43-HDS_D
B: derivatives/A-Gf_A67_43-HDS
a:  A-Gf_A67-43-HD_D
B: derivatives/A-Gf_A67_43-HD
a:  A-Gf_A64_43-HDS_M
a:  A-Gf_A64_43-HD_M
a:  A-Gf_A67_43-HDS_M
B: masters/A-Gf_A67_43-HDS
a:  A-Gf_A67-43-HDS_M
B: masters/A-Gf_A67_43-HDS
a:  A-Gf_A67-43-HD_M
B: masters/A-Gf_A67_43-HD

In [15]:
for i in random_list:
    parts = i.split('/')
    sub = df1.loc[df1["arche_id"].str.contains(parts[0])]
    if sub.loc[sub["arche_id"].str.contains(parts[1])].size < 1:
        print(i)

KeyboardInterrupt:

In [18]:
duplicates=[] 
for value in random_list:
  if random_list.count(value) > 1 and value not in duplicates:
     duplicates.append(value)
     print(value)
print(duplicates)

derivatives/A-Gf_A67_43-HDS
derivatives/A-Gf_S1_23-a001r
derivatives/A-Gf_S1_23-BR
derivatives/A-Gf_S1_23-HDS
derivatives/A-Gf_S1_23-VD
masters/A-Gf_A67_43-HDS
masters/A-Gf_S1_45-HD
['derivatives/A-Gf_A67_43-HDS', 'derivatives/A-Gf_S1_23-a001r', 'derivatives/A-Gf_S1_23-BR', 'derivatives/A-Gf_S1_23-HDS', 'derivatives/A-Gf_S1_23-VD', 'masters/A-Gf_A67_43-HDS', 'masters/A-Gf_S1_45-HD']

In [50]:
# Define a function to extract and transform values
df4 = pd.read_csv('handles_copy.csv')
def transform_content(cell_content):
    # Match the relevant segment within the content
    match = re.search(r"(A-Gf_[AS][0-9][0-9]*.*)", cell_content)
    if match:
        base_segment = match.group(1).replace(".tif", "")
        if "masters" in cell_content:
            unique_number = f"{base_segment}_M"  # Master
            title = f"{base_segment} (Master)"
        else:
            unique_number = f"{base_segment}_D"  # Derivative
            title = f"{base_segment} (Derivative)"
        return unique_number, title
    return None, None

# Apply the function to extract and fill the columns
df4["eindeutige Nummer des Digitalisats"], df4["Titel des Digitalisats"] = zip(
    *df4["Ressourcenadresse"].apply(lambda x: transform_content(x) if isinstance(x, str) else (None, None))
)

In [95]:
df5['Ressourcenadresse'] = df5['Kontextadresse'] + "?format=tif"

In [60]:
df5

,Fördernehmer_in,eindeutige Nummer des Digitalisats,Analogfilm,3D,Sonstige,Ressourcenadresse,Titel des Digitalisats,Kommentar (optional),Kontextadresse
0,Franziskanerkloster Graz,A-Gf_A63_51-000r_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0012-23AA...,A-Gf_A63_51-000r (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/A63...,https://hdl.handle.net/21.11115/0000-0012-23AA-5
1,Franziskanerkloster Graz,A-Gf_A63_51-000v_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0012-23AB...,A-Gf_A63_51-000v (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/A63...,https://hdl.handle.net/21.11115/0000-0012-23AB-4
2,Franziskanerkloster Graz,A-Gf_A63_51-001r_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0012-23AC...,A-Gf_A63_51-001r (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/A63...,https://hdl.handle.net/21.11115/0000-0012-23AC-3
3,Franziskanerkloster Graz,A-Gf_A63_51-001v_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0012-23AD...,A-Gf_A63_51-001v (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/A63...,https://hdl.handle.net/21.11115/0000-0012-23AD-2
4,Franziskanerkloster Graz,A-Gf_A63_51-002r_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0012-23AE...,A-Gf_A63_51-002r (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/A63...,https://hdl.handle.net/21.11115/0000-0012-23AE-1
...,...,...,...,...,...,...,...,...,...
35446,NaN,A-Gf_S1_22-BR_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0013-BB7A...,A-Gf_S1_22-BR (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/S1_...,https://hdl.handle.net/21.11115/0000-0013-BB7A-0
35447,NaN,A-Gf_A67-43-HDS_D,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0013-BDDB...,A-Gf_A67-43-HDS (Derivative),https://id.acdh.oeaw.ac.at/ofmgraz/derivatives...,https://hdl.handle.net/21.11115/0000-0013-BDDB-0
35448,NaN,A-Gf_S1_22-HDS_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0013-BDDA...,A-Gf_S1_22-HDS (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/S1_...,https://hdl.handle.net/21.11115/0000-0013-BDDA-1
35449,NaN,A-Gf_S1_22-VD_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0013-BDD9...,A-Gf_S1_22-VD (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/S1_...,https://hdl.handle.net/21.11115/0000-0013-BDD9-2
35450,NaN,A-Gf_S1_22-a001r_M,NaN,NaN,NaN,https://hdl.handle.net/21.11115/0000-0013-BDD8...,A-Gf_S1_22-a001r (Master),https://id.acdh.oeaw.ac.at/ofmgraz/masters/S1_...,https://hdl.handle.net/21.11115/0000-0013-BDD8-3

In [96]:
df5.to_csv('OFM_Graz.csv', index=False)

In [94]:
used = []
df5 = pd.read_csv('salida.csv')
h = handles[0:-1]


for index, row in df5.iterrows():
    #handle = False
    #while not handle:
    #    handle = h[-1].strip()
    #    h.pop(-1)
    #    used.append(handle)
    #    if df5.loc[df5["Kontextadresse"].str.contains(handle)].size > 1:
    #        row['Ressourcenadresse'] = handle
    #    else:
    #        handle = False
    if len(df2.loc[df2['Transformed Image Name'] == row['eindeutige Nummer des Digitalisats']]) > 0:
        if len(df5.loc[df5['eindeutige Nummer des Digitalisats'].str.contains(row['eindeutige Nummer des Digitalisats'])]) > 1:
            print(f'duplicate: {row["eindeutige Nummer des Digitalisats"]}')
    else:
        print(row['eindeutige Nummer des Digitalisats'])

duplicate: A-Gf_A67_43-148va_D
duplicate: A-Gf_A67_43-HDS_D
duplicate: A-Gf_A67_43-HDS_D
A-Gf_S1_22-VD_D
duplicate: A-Gf_A67_43-148va_D
A-Gf_A67-43-HDS_D

In [75]:
df2

,Fördernehmer_in,eindeutige Nummer des Digitalisats,Analogfilm,3D,Sonstige,Ressourcenadresse,Titel des Digitalisats,Kommentar (optional),Kontextadresse,Transformed Image Name
0,Franziskanerkloster Graz,A-Gf_A63_51-000v_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9112-2,A-Gf_A63_51-000v (derivative),https://hdl.handle.net/21.11115/0000-0013-9111-3,https://hdl.handle.net/21.11115/0000-0013-9111...,img_name_D
1,Franziskanerkloster Graz,A-Gf_A63_51-001r_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9114-0,A-Gf_A63_51-001r (derivative),https://hdl.handle.net/21.11115/0000-0013-9113-1,https://hdl.handle.net/21.11115/0000-0013-9113...,img_name_D
2,Franziskanerkloster Graz,A-Gf_A63_51-001v_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9116-E,A-Gf_A63_51-001v (derivative),https://hdl.handle.net/21.11115/0000-0013-9115-F,https://hdl.handle.net/21.11115/0000-0013-9115...,img_name_D
3,Franziskanerkloster Graz,A-Gf_A63_51-002r_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-9118-C,A-Gf_A63_51-002r (derivative),https://hdl.handle.net/21.11115/0000-0013-9117-D,https://hdl.handle.net/21.11115/0000-0013-9117...,img_name_D
4,Franziskanerkloster Graz,A-Gf_A63_51-002v_D,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-911A-A,A-Gf_A63_51-002v (derivative),https://hdl.handle.net/21.11115/0000-0013-9119-B,https://hdl.handle.net/21.11115/0000-0013-9119...,img_name_D
...,...,...,...,...,...,...,...,...,...,...
35421,Franziskanerkloster Graz,A-Gf_S1_76-027v_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-89D5-0,A-Gf_S1_76-027v (master),https://hdl.handle.net/21.11115/0000-0012-6B55-5,https://hdl.handle.net/21.11115/0000-0012-6B55...,img_name_M
35422,Franziskanerkloster Graz,A-Gf_S1_76-028v_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-89D7-E,A-Gf_S1_76-028v (master),https://hdl.handle.net/21.11115/0000-0012-6B57-3,https://hdl.handle.net/21.11115/0000-0012-6B57...,img_name_M
35423,Franziskanerkloster Graz,A-Gf_S1_76-VDS_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-89DB-A,A-Gf_S1_76-VDS (master),https://hdl.handle.net/21.11115/0000-0012-6B5C-E,https://hdl.handle.net/21.11115/0000-0012-6B5C...,img_name_M
35424,Franziskanerkloster Graz,A-Gf_S1_76-FKv_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-8CF8-6,A-Gf_S1_76-FKv (master),https://hdl.handle.net/21.11115/0000-0012-6B5A-0,https://hdl.handle.net/21.11115/0000-0012-6B5A...,img_name_M
35425,Franziskanerkloster Graz,A-Gf_S1_76-FKr_M,NaN,NaN,X,https://hdl.handle.net/21.11115/0000-0013-8CF7-7,A-Gf_S1_76-FKr (master),https://hdl.handle.net/21.11115/0000-0012-6B59-1,https://hdl.handle.net/21.11115/0000-0012-6B59...,img_name_M

In [76]:
   def transform_img_name(row):
    app = row['eindeutige Nummer des Digitalisats'][-1]
    img_name = row['eindeutige Nummer des Digitalisats']
    img_name = img_name.replace("Gu", "Gf")
    img_name = img_name.replace("Gu", "Gf").split(".jpg")[0]
    img_name = re.sub(r"^.*A-Gf_", "A-Gf_", img_name)[:-2]
    img_name = re.sub(r"^[\d_]*", "", img_name)
    img_name = re.sub(r"A-Gf_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = re.sub(r"A-Gf_A_([\d])", "A-Gf_A\g<1>", img_name)
    img_name = img_name.replace("view_IMG_0134", "A-Gf_S1_61-VDS").replace('A-Gf_64', 'A-Gf_A64').replace(' ', '').replace('%2B', '_')
    img_name = img_name.replace("67-43", "67_43").replace('.TIF', '').replace('S1_67_', "S1_67-")
    img_name = re.sub(r"(S1_22/A-Gf_S1_2)3", r"\g<1>2", img_name)
    img_name = re.sub(r"(A64_41.*\d)vv", r"\g<1>v", img_name)
    return f'{img_name}_{app}'

# Apply the transformation to the DataFrame
df2['Transformed Image Name'] = df2.apply(transform_img_name, axis=1)

In [ ]:
row_index = 1

# Get the row as a list
row_values = df5.iloc[''].tolist()

# Find duplicate values in the row
duplicates = [value for value in set(row_values) if row_values.count(value) > 1]